# ?? ??
#spring:
#  datasource:
#    driver-class-name: com.mysql.cj.jdbc.Driver
#    url: jdbc:mysql://127.0.0.1:3307/grabtable
#    username: root
#    password: 1208
#  jpa:
#    open-in-view: false
#    show-sql: true
#    hibernate:
#      ddl-auto: create

--- #local ??
spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:3307/grabtable
    username: root
    password: 1208
  jpa:
    open-in-view: false
    show-sql: true
    hibernate:
      ddl-auto: create
  auth:
    jwt:
      secretKey: grabtablegrabtablegrabtablegrabtablegrabtablegrabtablegrabtable #임시
      refreshTokenExpiry: 36000
      accessTokenExpiry: 3600
  oauth:
    kakao:
      adminkey: 5b41d5a0ea1ba89951211349a0b8f5bd

server.port: 8000