spring:
  data:
    mongodb:
      host: localhost
      port: 27017
  kafka:
    consumer:
      bootstrap-servers: kafka:9094
      group-id: reservation-history-group
  application:
    name: history-service
