name: Java CI with Gradle

on:
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:
  
defaults:
  run:
    working-directory: backend/grabtable
jobs:
  build:

    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
    - uses: actions/checkout@v4
      with:
        token: ${{secrets.ACTION_TOKEN}}
        submodules: true
    - name: Set up JDK 17
      uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'corretto'

    - name: Setup Gradle
      uses: gradle/actions/setup-gradle@417ae3ccd767c252f5661f1ace9f835f9654f2b5 # v3.1.0
      
    # - name: gradlew 권한 부여
    #   run: chmod +x gradlew
    
    - name: DB config 
      uses: mirromutth/mysql-action@v1.1
      with:
        host port: 3307
        container port: 3306
        mysql database: 'grabtable'
        mysql root password: ${{ secrets.DB_SECRET }}
        
    - name: Build with Gradle Wrapper
      run: ./gradlew build

    - name: jacocoTestCoverage
      id: jacoco
      uses: madrapps/jacoco-report@v1.5
      with:
        title: 📝 Jacoco Test Coverage
        paths: ${{ github.workspace }}/**/build/reports/jacoco/test/jacocoTestReport.xml
        token: ${{ secrets.ACTION_TOKEN }}
        min-coverage-overall: 50
        min-coverage-changed-files: 50
        update-comment: true
        
  dependency-submission:

    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
    - uses: actions/checkout@v4
    - name: Set up JDK 17
      uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'corretto'

    - name: Generate and submit dependency graph
      uses: gradle/actions/dependency-submission@417ae3ccd767c252f5661f1ace9f835f9654f2b5 # v3.1.0
