name: Nextjs CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 21
      
      - name: Install frontend packages
        working-directory: ./frontend/grabtable
        run: npm install

      - name: Check frontend code style
        working-directory: ./frontend/grabtable
        run: npm run check
      
      - name: Check frontend code build
        working-directory: ./frontend/grabtable
        run: npm run build